# Generated by Django 6.0.4 on 2026-05-07 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_quizscore_userprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolesson',
            name='youtube_url',
            field=models.URLField(help_text='Paste the YouTube video link or iframe code here.', max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
    ]
