# Generated by Django 6.0.4 on 2026-05-28 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_videolesson_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolesson',
            name='youtube_url',
            field=models.CharField(help_text='Paste the YouTube video link or iframe code here.', max_length=500, validators=[django.core.validators.RegexValidator(message='Error: Only YouTube links or iframe codes are allowed!', regex='(youtube\\.com|youtu\\.be|<iframe)')]),
        ),
    ]
