# Generated by Django 6.0.4 on 2026-06-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_covers/'),
        ),
    ]
