# Generated by Django 6.0.4 on 2026-06-25 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_quiz_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizscore',
            name='pathway',
        ),
        migrations.AddField(
            model_name='quizscore',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.quiz'),
        ),
    ]
